### PR TITLE
Define headers to be replaced

### PR DESCRIPTION
**Pull request by tinect**
you should explicit replace the headers, due to duplicated entries at forwarded requests

### CODE REVIEW

**Comment by DanielRuf** [comment]
This can be in some parts be irritating if you have additional settings in your .htaccess, vhost and Apache conf files, WAF and so on.

I think it is better to add boolean settings for each option to set this for every header on demand.

**Comment by DanielRuf** [comment]
For example we use some WAFs which add these headers already and this would not append but replace the rules (like CSP and so on).

**Comment by tinect** [comment]
Sounds like a legit way, but the way could be: deactivate the header in plugin, if it's always set by yourself
Couldn't it?
This is the setting, you should use. I think there are settings enough. ;-)

**Comment by DanielRuf** [comment]
> Sounds like a legit way, but the way could be: deactivate the header in plugin, if it's always set by yourself

Sure, but keep in mind that not everybody who can configure the plugin (backend user) can also see and update .htaccess, php.ini and so on and do not know what is set by the server admin or technical officer.

**Comment by DanielRuf** [comment]
> Update Frontend.php

The PR title could be a bit more verbose.
There is the title field at the bottom. I generally recommend to use Git on the terminal. The last commit can be amended with `git commit --amend` to change the message to a better explanation of the proposed changes. Just my two cents for a better PR.

> verified signature using GitHub’s key.

**Comment by tinect** [comment]
> Sure, but keep in mind that not everybody who can configure the plugin (backend user) can also see and update .htaccess, php.ini and so on and do not know what is set by the server admin or technical officer.

This plugin shouldn't be used and configured by an default "backend user", that's the reason why this plugin isn't in store. No one should use or configure things, they don't know about. We cannot safe the world from `DAU`s.

**Comment by DanielRuf** [comment]
> This plugin shouldn't be used and configured by an default "backend user", that's the reason why this plugin isn't in store. No one should use or configure things, they don't know about. We cannot safe the world from `DAU`s.

I did not mean a "default" backend user. There is still a difference between a server admin / CTO and a admin user for the shop but with no further technical knowhow ;-)

**Comment by DanielRuf** [comment]
> that's the reason why this plugin isn't in store

Well, even those can download a zipped release and easily upload it in the backend.

**Comment by larsbo** [comment]
> Well, even those can download a zipped release and easily upload it in the backend.

Sure, but we can't stop them if they're not supposed to. Downloading things and install them without knowledge is a popular activity. 😟 

> Sure, but keep in mind that not everybody who can configure the plugin (backend user) can also see and update .htaccess, php.ini and so on and do not know what is set by the server admin or technical officer.

That's a project related edge case in my opinion. It should not be task of the plugin to solve internal communication issues.

**Comment by kielcoding** [comment]
@tinect thank you for the contribution!

**Pull request merged**
